# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: serverless
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5434:5432